name: Build and Release Android App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Decode Keystore File
      run: echo "${{ secrets.KEYSTORE }}" | base64 -d > my-release-key.keystore

    - name: Build Release APK
      run: |
        ./gradlew assembleRelease -Pandroid.injected.signing.store.file=my-release-key.keystore -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} -Pandroid.injected.signing.key.alias=${{ secrets.ALIAS }} -Pandroid.injected.signing.key.password=${{ secrets.KEY_PASSWORD }}
      
    - name: Upload Release APK
      uses: actions/upload-artifact@v2
      with:
        name: release-apk
        path: app/build/outputs/apk/release/app-release.apk
