name: Deploy to Firebase Hosting

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only hosting --project {{FIREBASE_PROJECT_ID}}
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
